--- arch/arm/mach-msm/Makefile
+++ arch/arm/mach-msm/Makefile
@@ -74,3 +74,5 @@ obj-$(CONFIG_MSM_SMCMOD) += smcmod.o
 obj-$(CONFIG_ARCH_MSM8974) += msm_mpmctr.o
 
 obj-$(CONFIG_PERFMAP) += perfmap.o
+
+obj-$(CONFIG_HAS_MACH_MEMUTILS) += memutils/
