vpath %.c $(SRCDIR)/swp

SWPTEST_CFLAGS := $(CFLAGS)
SWPTEST_CFLAGS += $(QCT_CFLAGS)

SWPTEST_CPPFLAGS := $(CPPFLAGS)
SWPTEST_CPPFLAGS += $(QCT_CPPFLAGS)

SWPTEST_LDLIBS := $(LDLIBS)
SWPTEST_LDLIBS += -lstringl

APP_NAME := swp_test
SRCLIST  := swp_test.c

all: $(APP_NAME)

$(APP_NAME): $(SRCLIST)
$(CC) $(SWPTEST_CFLAGS) $(SWPTEST_CPPFLAGS) $(LDFLAGS) -o $@ $^ $(SWPTEST_LDLIBS)
