--- drivers/clk/msm/Makefile
+++ drivers/clk/msm/Makefile
@@ -45,12 +45,12 @@ obj-$(CONFIG_ARCH_MDMCALIFORNIUM)	+= clock-a7.o
 obj-$(CONFIG_ARCH_MDM9607)	+= clock-a7.o
 obj-$(CONFIG_ARCH_MSM8916)	+= clock-a7.o
 obj-$(CONFIG_ARCH_MSM8909)	+= clock-a7.o
-obj-$(CONFIG_ARCH_MSM8916)	+= clock-cpu-8939.o
+#obj-$(CONFIG_ARCH_MSM8916)	+= clock-cpu-8939.o
 obj-$(CONFIG_ARCH_MSM8916)	+= clock-cpu-8936.o
-obj-$(CONFIG_ARCH_MSM8916)	+= clock-gcc-8952.o
-obj-$(CONFIG_ARCH_MSM8916)	+= clock-gcc-titanium.o
+#obj-$(CONFIG_ARCH_MSM8916)	+= clock-gcc-8952.o
+#obj-$(CONFIG_ARCH_MSM8916)	+= clock-gcc-titanium.o
 obj-$(CONFIG_ARCH_MSM8916)	+= clock-rcgwr.o
-obj-$(CONFIG_ARCH_MSM8916)      += clock-cpu-titanium.o
+#obj-$(CONFIG_ARCH_MSM8916)      += clock-cpu-titanium.o
 
 obj-y				+= gdsc.o
 obj-y				+= mdss/
